---
title: Correlation between Cycle Hire Trips and the Terrain
bibliography: bio.bib
csl: harvard-cite-them-right.csl
execute: 
  echo: false
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: Spectral
    sansfont: Roboto
    monofont: JetBrainsMono-Regular
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github    
---

# QM Written assignment

## Introduction

Cycle hire schemes are spreading rapidly in cities in the 21st century. This has greatly impacted the transport system in cities, by increasing the share of cycling and public transport usage, lowering greenhouse gas emmisions, and improving public health [@demaio2009]. Since the first implication of the cycle hire scheme in Amsterdam in the 1960s, the system has seen technological and methodological improvements over time. The modern system equipped with electronic self-serve docking stations and integration with technology has enabled users to use cycles between different stations, allowing for casual usages for short, high-frequency and one-way journeys[@beecham2015; @beroud2012].

The London Cycle Hire Scheme (LCHS), widely known as the Santander Cycles, is one of these systems. In service since 2010 [@li2019], it has 800 docking stations within central London [@transportforlondon2023a]. Users are charged on a timed basis for one-time usage, or can opt into memberships allowing unlimited rides up to 60 minutes at a time [@transportforlondonb]. 

## Literature Review

The detailed datasets of cycle hire schemes such as LCHS around the world has enabled analysis for cycling behaviour from many aspects. @gebhart2014 has explored how weather conditions affect the number of bikeshare trips in Washington DC, finding uncomfortable conditions including cold weather, precipitation, and high humidity reduces bikeshare usage. @wood2011 explored the visualisation of journeys taken by the LCHS, illustrating two major patterns of usage: leisure usage often seen near Royal Parks and commuting to and from major train stations in peak hours.

Meanwhile, research on the relationship between cycling behaviour and the physical environment is limited. @rodriguez2004 explored the impacts of the physical environment such as the topography and the existence of sidewalks and bike paths to modal choices, and have found that a positive slope (uphill) reduces the odds of walking or cycling. This research surveyed the students and staff at a university, which may show a different behaviour from the general public.

Drawing on these two streams, this report has conducted an anlysis on the less-explored relationship between cycle hire scheme usage behaviour and the physical environment.

## Research Question

Is there a correlation between the quantity or duration of cycle hire trips and the slope of the physical environment?

## Hypothesis

The trips involving uphill paths will be discouraged, thus leading to a smaller number of trips done by the cycle hire scheme.

## Data

### Data Sources

Transport for London (TfL) makes data for the LCHS publicly available. The location of the 800 docking stations is available from the TfL Unified API [@transportforlondon2023a], where real time availability is updated along with the name, ID, and the number of docks each station has. Usage data is shared on their website as well [@transportforlondon2023], with the ID and name for start and end stations, date and time, duration, and type of cycle (conventional or e-cycle) for every journey taken by the LCHS.

The spatial data is joined by the physical attributes from other resources to extract the required information. LIDAR Composite Digital Terrain Model (DTM) [@environmentalagency2023] with a resolution of 2 m was used for extracting elevation. Statistical boundaries and congestion charge boundaries used are from the London Datastore [@greaterlondonauthority2014; @greaterlondonauthority2019].

Accessibility by other public transport modes also impact the usage of bicycle hire schemes [@gebhart2014]. In London, the accessibility by public transport (buses, rail, tube, and tram) is evaluated by an Access Index assigned to each 100 m grid within the Greater London area, which is then categorised into Public Transport Accessibility Levels (PTAL) [@transportforlondon2015a]. We will use the Access Index published by @transportforlondon2015 for each docking station.

### Summary of data

The scope of analysis is the journeys taken on the LCHS from December 2022 to November 2023, the most recent one-year period where data is available. There is a total of 8,414,631 journeys taken during this period, of which .

The summary of the data is shown as follows.

| Statistics | Classic Cycles | E-cycles | Total |
|===|---|---|---|
| Number of Trips | 7,808,234 | 606,397 | 8,414,631 |
| Mean Travelled Distance [m] | 2279.41 | 3124.62 | 2340.32 |
| Mean Height Difference [m] | -0.23 | -0.07 | -0.22 |

: **Table 1**: Characteristics of journeys made by the LCHS 

As a whole, the average height difference between the origin and destination is -0.22 metres, a slight negative value indicating downhill travel is slightly preferred over their uphill counterparts. Different behaviour can be observed for the classic cycles and e-cycles in terms of distance and height difference. Longer distance and the smaller difference in height infer e-cycles allows journeys more physically demanding to the cyclists. From this comparison between the classic cycles and e-cycles, we believe that the physical intensity of cycling may have a correlation on the journeys taken on the LCHS.

There are many factors that influence the choice of travel mode, and we cannot immediately conclude the height difference is the decisive factor. This report will attempt to identify the effect of the height difference on the journeys. From this point, our focus will be on journeys made by classic cycles.

### Spatial Distribution of Cycling Behaviour

The spatial characteristics (although not the main focus of this report) is an important aspect of cycling behaviour. We will define Central London as the congestion charge zone [@transportforlondon] which is roughly the area within the Ring Road. The following table shows the characteristics of journeys, classified by their relation to the Central London area.

| Origin: | Outside || Inside ||
| Destination: | Outside | Inside | Outside | Inside |
|===|---|---|---|---|
| Number of Trips | 3,788,352	| 1,432,552 | 1,265,977 | 1,927,750 |
| Mean Travelled Distance [m] | 1972.20 | 3290.51 | 3294.99 | 1730.68 |
| Mean Height Difference [m] | -0.17 | -0.04 | -0.73 | -0.11 |

: **Table 2**: Number of Journeys made by all cycles in relation with the Congestion Charge Zone

Comparing the journeys that start outside the central area and finish within the central area (hereinafter inbound journeys) to the ones originating at the center and terminating outside (outbound journeys), there are less outbound journeys indicating cycling is not chosen as the mode of transport, despite the fact that outbound journeys tend to be more downhill (larger difference in mean height difference.)
Although the reason behind this is unknown and out of the scope of this research (one brave assumption may be that commuters do not wish to engage in cycling after their working hours), this is one parameter we must consider in further analysis.

## Methodology

### Summarizing the data into Origin-Destination pairs

In order to conduct a quantitative analysis on the amount of journeys taken by cyclists, we will summarise the data by grouping them according to their origin and destination. For this analysis, MSOAs will be used as the unit of analysis.  We have first grouped the journeys by origin and destination by docking stations, then regrouping them based on MSOA of their origin and destination. 
There are 160 MSOAs where at least one docking station exists, therefore the summarised dataset includes 25,600 rows of data. By removing journeys that start and finish within the same MSOA, we have 25,440 rows of data for analysis.

#### Subsetting dataset for initial analysis

Considering the whole origin-destination matrix will include various factors unidentified, thus we will first conduct the analysis on a subset of the dataset. We will extract the journeys involving specific MSOAs as a starting point, and conduct an analysis on the subset. The results acquired will be applied to the whole matrix afterwards for further analysis.
Two subsets were created for this first analysis: journeys involving the City of London (code: E02000001) at the center of the city, and involving the MSOA of Primrose Hill (E02000183) in the Borough of Camden outside the cental zone.

### Explanatory factors

In order to analyse the impact of the height difference, a multiple regression model is conducted to differentiate the impacts of height difference from other explanatory variables. Other potential explanatory variables are listed as follows:

- distance of journey
- population density
- access to public transport
- number of ports in MSOA
- direction of journey

When considering the subset using one MSOA as the origin or destination, characteristics for the other end of the journey was stored for regression. Upon analysis for the whole dataset, the characteristics for origin and destination were both used to consider the impact. The direction of journey for the whole dataset will be represented by the ratio of stations within the central zone, due to the fact that some MSOAs stretch through the borders of the central zone defined. 

#### Analysis of variables

The scatter plots for each of the potential explanatory variables are shown as follows.

The scatter plot suggests the distance may have a power law correlation with the number of journeys. A linear regression on log-log scale returns a coefficient of -2.3, indicating the inverse squared value of distance may have a better correlation with the number of journeys. Assuming other variables have a linear correlation (if any at all), the following model will be used for further analysis.

$$
y = \frac{\beta_{\text{dist}}}{(x_{\text{dist}})^2} + \sum_i{\beta_ix_i}
$$

- $x_{\text{dist}}$: distance of journey
- $x_i$: other explanatory variables
- $\beta$: coefficients

By storing the inverse squared value of distance (/km^2^) in the `distance_inv_sq` variable, the linear regression model will consist of the following dependent variables.

| Criteria | Variables (subset analysis) | Variables (whole dataset analysis) |
|===|---|---|
| independent variable (number of journeys) | `Number` ||
| distance of journey | `distance_inv_sq` ||
| population density | `other_pop` | `start_pop` `end_pop` |
| access to public transport (Access Index) | `other_AI2015 ` | `start_AI2015` `end_AI2015` |
| number of stations in MSOA | `other_stations` | `start_stations` `end_stations` |
| ratio of stations within central zone | - | `start_cc_zone` | `end_cc_zone` |
| direction of journey | `is_outbound` | - |

: Variables for linear regression analysis

## Results

### Analysis of subset

#### Subset 1: City of London

We will first consider the analysis on the journeys to and from the City of London.

The correlation matrix for each dependent variable and the independent variable are shown in the figure below.

All coefficients are below 0.8, indicating there is no multicollinearity between dependent variables. The variance inflation factors for each variable do not exceed the threshold of 5, justifying all variables for linear regression. The results of the regression model is as follows:

| Variable | Coefficient | Standard Error | $t$ | $P > |t|$ |
|:===|---:|---:|---:|---:|
| Constant | -2422.6827 | 745.016 | -3.252 | 0.001 |
| `distance_inv_sq` | 23128.98 | 2094.249 | 11.044 | 0.000 |
| `height_diff` | 0.7890 | 20.102 | 0.039 | 0.969 |
| `other_stations` | 542.9293 | 60.293 | 9.005 | 0.000 |
| `other_AI2015` | 35.3196 | 11.515 | 3.067 | 0.002 |
| `other_pop` | -0.0210 | 0.039 | -0.546 | 0.586 |
| `is_outbound` | -291.4769 | 361.979 | -0.805 | 0.421 |

: Coefficient table for linear regression model for journeys to/from City of London

The adjusted R-squared value of this regression model is $R^2 = 0.623$. 
The distance, the number of stations in area, the accessibility by public transport are the significant factors that impact the number of journeys taken. On the other hand, the height difference, the population density, and the direction is insignificant.

#### Subset 2: Primrose Hill, Camden

The MSOA of Primrose Hill is a residential district located just north of Regent's Park, and is at the northern edge of the area covered by LCHS. This was chosen as an example of an area outside the center area to contrast with the above example of the City of London. The correlation matrix for journeys to/from this area is shown below.

There is a high negative correlation between the direction of travel and the height difference, due to the high elevation of this area. The `is_outbound` variable indicating direction was removed during the VIF analysis. The results of the regression model for this area is shown as follows.

| Variable | Coefficient | Standard Error | $t$ | $P > |t|$ |
|:===|---:|---:|---:|---:|
| Constant | -76.7718 | 42.219 | -1.818 | 0.070 |
| `distance_inv_sq` | 425.2467 | 49.771 | 8.544 | 0.000 |
| `height_diff` | -0.1126 | 0.523 | -0.215 | 0.830 |
| `other_stations` | 22.6144 | 3.068 | 7.371 | 0.000 |
| `other_AI2015` | 2.001 | 0.671 | 2.983 | 0.003 |
| `other_pop` | -0.0017 | 0.002 | -0.760 | 0.448 |

: Coefficient table for linear regression model for journeys to/from Primrose Hill, Camden

The adjusted R-squared value is $R^2 = 0.440$, smaller than that for the City of London. The significance of variables show a similar pattern, with the distance, number of stations in an area, and the accessibility by public transport being significant, while the height difference and population density being insignificant.

#### Checking the assumptions of linear regression

The residual vs fitted plot and the histogram of residuals are shown below for both areas.

Overall, the normal distribution of errors and the homoscedasticity assumption are met, with the exception of a few outliers that have higher values than predicted. We can conclude that the linear regression model is a legitimate model that partially explains the cycling behaviour.

### Analysis of the dataset as a whole

We have extracted 2 areas as the focus for the linear regression model, and have seen that the factors explained have some explanatory power when applied to journeys involving particular areas. We will now apply this to the original dataset as a whole.

The correlation matrix is shown as follows:



There is a collinearity between the number of stations per area, the accessibility by public transport, and whether the docks are in the central area, although this is below the threshold of 5 for a VIF analysis. The results of the regression model is as follows:

| Variable | Coefficient | Standard Error | $t$ | $P > |t|$ |
|:===|---:|---:|---:|---:|
|Constant|-482.8715|30.011|-16.090|0.000|
|`distance_inv_sq`|817.9024|16.343|50.046|0.000|
|`height_diff`|-0.4716|0.422|-1.119|0.263|
|`start_stations`|61.4233|1.621|37.884|0.000|
|`end_stations`|66.8177|1.621|41.211|0.000|
|`start_AI2015`|1.0362|0.353|2.933|0.003|
|`end_AI2015`|1.0950|0.353|3.100|0.002|
|`start_pop_density`|-0.0009|0.001|-0.831|0.406|
|`end_pop_density`|-0.0020|0.001|-1.866|0.062|
|`start_cc_zone`|21.5298|23.612|0.912|0.362|
|`end_cc_zone`|22.7766|23.612|0.965|0.335|

The adjusted R-squared value is $R^2 = 0.283$ showing that 28.3 % of the difference can be explained through these factors. The significant variables are the distance, number of stations and the accessibility to public transport, which is linear with the subsets observed. The difference in height, along with the population density and the relationship with the central zone is not a significant factor.

## Discussion

The regression model we have considered has successfully defined several factors that influence the number of cycle hire journeys between MSOAs: the distance, the number of stations, and the accessibility to public transport. Meanwhile, the population density, location, and height difference were not statistically significant, although it is worth noting the population density of the end points had lower P-value compared to that of origin.

When applied to the spatial subset of the dataset, our regression model had a larger R-squared value, indicating that impacts individual characteristics of the areas must be investigated further. Potential areas of exploration not addressed in this report include user analysis, purpose of travel, time of day, usage of public transport, and other socioeconomic factors of the area. From the perspective of the service provided, the availability of cycles and vacant ports may also influence usage.

In all cases, we could not find a significant correlation between the difference of the height and the quantity of travel, although the average difference indicated an overall preference to downhill travel. One reason may be that the simple difference of elevation between end points is not representing the uphill slope that impacts the choice of travel. An ideal conceptual approach is to consider the uphill and downhill segments appearing en route, but further consideration is needed for the methodology and feasibility. A second approach, with focus to the choice of docking stations within local areas, is to consider the relative elevation to neighbouring docking stations in relationship with its usage. Meanwhile, there is also the possibility that elevation is not a decisive factor to the frequency, and a result of other influencing variables.

## Conclusion

In this research, we have created a dataset of journeys taken by the LCHS, with added information on the elevation and accessibility to public transport for origins and destinations of each journey. Although the summary statistics seem to indicate some relationship, we could not find a statistically significant influence of elevation difference to the number of journeys taken between points. The field of studying cycling behaviour through cycle hire data is growing rapidly [@beecham2015], and further research is expected for the better understanding of the effect of the physical environment on cycle hire flows.

## Reference


